<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- Exclude generated code and migrations from coverage -->
        <CodeAnalysisExcludeGeneratedCode>true</CodeAnalysisExcludeGeneratedCode>
    </PropertyGroup>

    <!-- Exclude migrations from code coverage -->
    <ItemGroup>
        <Compile Update="Migrations\**\*.cs" ExcludeFromCodeCoverage="true" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\IDataAccess\IDataAccess.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
