<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>obligatorio_parque_tematico_virtual</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\ApiServiceFactory\ApiServiceFactory.csproj" />
      <ProjectReference Include="..\Models\Models.csproj" />
      <ProjectReference Include="..\IBusinessLogic\IBusinessLogic.csproj" />
    </ItemGroup>

</Project>
