on:
  workflow_call:
    inputs:
      solution-path:
        type: string
        description: "The relative path to the .sln file (default: current directory)"
        required: false
        default: "."
      solution-name:
        type: string
        description: "The name of the solution file (e.g., MyApp.sln)"
        required: true
      report-coverage-title:
        type: string
        description: "A title for the coverage report (default: Reporte de Cobertura)"
        required: false
        default: "Reporte de Cobertura"

env:
  DOTNET_VERSION: "8.0.x" # The .NET SDK version to use
  FULL_SOLUTION_PATH: ${{ inputs.solution-path }}/${{ inputs.solution-name }}

jobs:
    can_run:
      name: Check Can Run
      runs-on: ubuntu-latest
      timeout-minutes: 2
      outputs:
        buildLabelOff: ${{ env.buildLabelOff }}
        testsLabelOff: ${{ env.testsLabelOff }}
        analysisLabelOff: ${{ env.analysisLabelOff }}

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set Labels
          run: |
            buildLabelOff=${{ !contains(github.event.pull_request.labels.*.name, 'Blocked: Build Fix Required') }}
            testsLabelOff=${{ !contains(github.event.pull_request.labels.*.name, 'Blocked: Tests Fix Required') }}
            analysisLabelOff=${{ !contains(github.event.pull_request.labels.*.name, 'Blocked: Analysis Fix Required') }}

            echo "buildLabelOff=${buildLabelOff}" >> $GITHUB_ENV
            echo "testsLabelOff=${testsLabelOff}" >> $GITHUB_ENV
            echo "analysisLabelOff=${analysisLabelOff}" >> $GITHUB_ENV

    build:
      name: Build
      needs: can_run
      permissions: write-all
      runs-on: ubuntu-latest
      timeout-minutes: 5

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Check If Blocked Label Exists
          if: ${{ needs.can_run.outputs.buildLabelOff == 'false' || needs.can_run.outputs.testsLabelOff == 'false' || needs.can_run.outputs.analysisLabelOff == 'false' }}
          run: |

            if [[ "${{ needs.can_run.outputs.buildLabelOff }}" == "false" ]]; then
              echo "Build blocked label exists."
            fi

            if [[ "${{ needs.can_run.outputs.testsLabelOff }}" == "false" ]]; then
              echo "Tests blocked label exists."
            fi

            if [[ "${{ needs.can_run.outputs.analysisLabelOff }}" == "false" ]]; then
              echo "Analysis blocked label exists."
            fi

            exit 1

            echo "buildLabelOff=${{ needs.can_run.outputs.buildLabelOff }}"
            echo "testsLabelOff=${{ needs.can_run.outputs.testsLabelOff }}"
            echo "analysisLabelOff=${{ needs.can_run.outputs.analysisLabelOff }}"

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Install dependencies
          run: dotnet restore ${{ env.FULL_SOLUTION_PATH }}

        - name: Run build
          run: dotnet build ${{ env.FULL_SOLUTION_PATH }} --configuration Release

        # 🛑 Add "Blocked: Fix Required" label if tests fail
        - name: Block PR if Build Fail
          if: ${{ failure() && github.event_name == 'pull_request' && needs.can_run.outputs.buildLabelOff == 'true' && needs.can_run.outputs.testsLabelOff == 'true' && needs.can_run.outputs.analysisLabelOff == 'true' }}
          run: |
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
              -d '{"labels":["Blocked: Build Fix Required"]}'

          # 📝 Comment on PR when blocked
        - name: Comment on PR if Build Fail
          if: ${{ failure() && github.event_name == 'pull_request' && needs.can_run.outputs.buildLabelOff == 'true' && needs.can_run.outputs.testsLabelOff == 'true' && needs.can_run.outputs.analysisLabelOff == 'true' }}
          uses: marocchino/sticky-pull-request-comment@v2
          with:
            recreate: true
            message: |
              ❌ The build failed. The PR has been marked as **Blocked: Build Fix Required**. Please fix the issues before pushing again.

    test:
      name: Test
      permissions: write-all
      needs: [build, can_run]
      runs-on: ubuntu-latest
      timeout-minutes: 5

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Check for Source Code Files
          run: |
            # Find source code files excluding Program.cs, Migrations, and *DbContext.cs, *Context.cs
            SOURCE_FILES=$(find ${{ inputs.solution-path }} -type f -name "*.cs" \
              ! -name "Program.cs" \
              ! -name "*DbContext.cs" \
              ! -name "*Context.cs" \
              ! -path "*/Migrations/*")

            if [[ -n "$SOURCE_FILES" ]]; then
              echo "🔍 Source code files found, tests will be required."
              echo "required_tests=true" >> $GITHUB_ENV
            else
              echo "✅ No significant source code found, tests are not required."
              echo "required_tests=false" >> $GITHUB_ENV
            fi

        - name: Generate Results and Coverage Reports
          if: ${{ env.required_tests == 'true' }}
          run: dotnet test ${{ env.FULL_SOLUTION_PATH }} --configuration Release --verbosity normal --logger "trx;LogFilePrefix=test-results" --results-directory ${{ inputs.solution-path}}/test-results --collect:"XPlat Code Coverage" --settings .runsettings

        - name: Uploaded Results Report
          if: ${{ always() && env.required_tests == 'true' }}
          uses: dorny/test-reporter@v1
          with:
            name: Uploaded Results Report
            path: ${{ inputs.solution-path }}/test-results/test-results*.trx
            reporter: dotnet-trx
            path-replace-backslashes: false
            list-suites: all
            list-tests: all
            max-annotations: 10
            fail-on-error: true
            fail-on-empty: true
            only-summary: false

        # - name: Remove Runner Folder
        #   if: ${{ env.required_tests == 'true' }}
        #   run: find ./test-results -type d -name "*_*_*" -exec rm -rf {} +

        - name: Join Coverage Reports
          if: ${{ env.required_tests == 'true' }}
          uses: danielpalme/ReportGenerator-GitHub-Action@5.3.9
          with:
            reports: ${{ inputs.solution-path }}/test-results/**/coverage.cobertura.xml
            targetdir: coverage-report
            reporttypes: "Html;Cobertura"
            verbosity: "Verbose"
            tag: "${{ github.run_number }}_${{ github.run_id }}"
            title: "${{ inputs.report-coverage-title }}"

        - name: Upload Coverage Report
          if: ${{ env.required_tests == 'true' }}
          uses: actions/upload-artifact@v4
          with:
            name: Coverage Report
            path: coverage-report

        - name: Check Coverage
          if: ${{ env.required_tests == 'true' }}
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: coverage-report/Cobertura.xml
            badge: true
            fail_below_min: true
            format: markdown
            hide_branch_rate: false
            hide_complexity: true
            indicators: true
            output: both
            thresholds: "85 90"

        - name: Add Coverage as PR Comment
          uses: marocchino/sticky-pull-request-comment@v2
          if: ${{ always() && github.event_name == 'pull_request' && env.required_tests == 'true' }}
          with:
            header: build-test
            recreate: true
            message: |
              ${{ hashFiles('code-coverage-results.md') != '' && '### Code Coverage Report\n\n' || '⚠️ Code coverage report not found. Tests required.' }}
            path: ${{ hashFiles('code-coverage-results.md') != '' && 'code-coverage-results.md' || '' }}

        - name: Write to Job Summary
          if: ${{ always() && env.required_tests == 'true'}}
          run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

        # 🛑 Add "Blocked: Fix Required" label if tests fail
        - name: Block PR if Tests Fail
          if: ${{ failure() && github.event_name == 'pull_request' && env.required_tests == 'true'}}
          run: |
            PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
              -d '{"labels":["Blocked: Tests Fix Required"]}'

        # 📝 Comment on PR when blocked
        - name: Comment on PR if Tests Fail
          if: ${{ failure() && github.event_name == 'pull_request' && env.required_tests == 'true' }}
          uses: marocchino/sticky-pull-request-comment@v2
          with:
            header: build-test
            append: true
            message: |
              ❌ The tests failed. The PR has been marked as **Blocked: Tests Fix Required**. Please fix the issues before pushing again.
